src/Entity/CourseGestion/Article.php
<?php

namespace App\Entity\CourseGestion;

use App\Repository\CourseGestion\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?course $id_cours = null;
    #[ORM\Column]
    private ?int $index = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIndex(): ?int
    {
        return $this->index;
    }

    public function setIndex(int $index): static
    {
        $this->index = $index;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getIdCours(): ?course
    {
        return $this->id_cours;
    }

    public function setIdCours(?course $id_cours): static
    {
        $this->id_cours = $id_cours;

        return $this;
    }


}

src/Entity/CourseGestion/Certificate.php
<?php

namespace App\Entity\CourseGestion;

use App\Entity\UserGestion\NormalUser;

use App\Repository\CourseGestion\CertificateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CertificateRepository::class)]
class Certificate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?course $id_Course = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToMany(targetEntity: NormalUser::class, mappedBy: 'Certifcates')]
    private Collection $cerfified_users;

    public function __construct()
    {
        $this->cerfified_users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getIdCourse(): ?course
    {
        return $this->id_Course;
    }

    public function setIdCourse(?course $id_Course): static
    {
        $this->id_Course = $id_Course;

        return $this;
    }

    /**
     * @return Collection<int, NormalUser>
     */
    public function getCerfifiedUsers(): Collection
    {
        return $this->cerfified_users;
    }

    public function addCerfifiedUser(NormalUser $cerfifiedUser): static
    {
        if (!$this->cerfified_users->contains($cerfifiedUser)) {
            $this->cerfified_users->add($cerfifiedUser);
            $cerfifiedUser->addCertifcate($this);
        }

        return $this;
    }

    public function removeCerfifiedUser(NormalUser $cerfifiedUser): static
    {
        if ($this->cerfified_users->removeElement($cerfifiedUser)) {
            $cerfifiedUser->removeCertifcate($this);
        }

        return $this;
    }


}

src/Entity/CourseGestion/Comment.php
<?php

namespace App\Entity\CourseGestion;

use App\Entity\UserGestion\GlobalUser;

use App\Repository\CourseGestion\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?course $id_course = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'Comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?GlobalUser $Users = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getIdCourse(): ?course
    {
        return $this->id_course;
    }

    public function setIdCourse(?course $id_course): static
    {
        $this->id_course = $id_course;

        return $this;
    }

    public function getUsers(): ?GlobalUser
    {
        return $this->Users;
    }

    public function setUsers(?GlobalUser $Users): static
    {
        $this->Users = $Users;

        return $this;
    }

}

src/Entity/CourseGestion/RoadMap.php
<?php

namespace App\Entity\CourseGestion;

use App\Entity\UserGestion\NormalUser;

use App\Repository\CourseGestion\RoadMapRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RoadMapRepository::class)]
class RoadMap
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $rate = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    #[ORM\ManyToMany(targetEntity: Course::class, inversedBy: 'roadMaps')]
    private Collection $courses;

    #[ORM\ManyToMany(targetEntity: NormalUser::class, mappedBy: 'RoadMaps')]
    private Collection $users;

    public function __construct()
    {
        $this->courses = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRate(): ?float
    {
        return $this->rate;
    }

    public function setRate(float $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Course>
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): static
    {
        if (!$this->courses->contains($course)) {
            $this->courses->add($course);
        }

        return $this;
    }

    public function removeCourse(Course $course): static
    {
        $this->courses->removeElement($course);

        return $this;
    }

    /**
     * @return Collection<int, NormalUser>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(NormalUser $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addRoadMap($this);
        }

        return $this;
    }

    public function removeUser(NormalUser $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeRoadMap($this);
        }

        return $this;
    }

}

src/Entity/CourseGestion/Video.php
<?php

namespace App\Entity\CourseGestion;

use App\Repository\CourseGestion\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $index = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(length: 255)]
    private ?string $data = null;

    #[ORM\ManyToOne(inversedBy: 'videos')]
    private ?Course $id_Course = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIndex(): ?int
    {
        return $this->index;
    }

    public function setIndex(int $index): static
    {
        $this->index = $index;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getData(): ?string
    {
        return $this->data;
    }

    public function setData(string $data): static
    {
        $this->data = $data;

        return $this;
    }

    public function getIdCourse(): ?Course
    {
        return $this->id_Course;
    }

    public function setIdCourse(?Course $id_Course): static
    {
        $this->id_Course = $id_Course;

        return $this;
    }

}

src/Entity/EventGestion/Competition.php
<?php

namespace App\Entity\EventGestion;

use App\Repository\EventGestion\CompetitionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompetitionRepository::class)]
class Competition
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Location = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $Groupe = null;

    #[ORM\ManyToOne(inversedBy: 'competitions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Event $event = null;

    #[ORM\OneToMany(mappedBy: 'competition', targetEntity: GroupCompetition::class, orphanRemoval: true)]
    private Collection $Groups;

    public function __construct()
    {
        $this->Groups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(string $Location): static
    {
        $this->Location = $Location;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getGroupe(): ?int
    {
        return $this->Groupe;
    }

    public function setGroupe(int $Groupe): static
    {
        $this->Groupe = $Groupe;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): static
    {
        $this->event = $event;

        return $this;
    }

    /**
     * @return Collection<int, GroupCompetition>
     */
    public function getGroups(): Collection
    {
        return $this->Groups;
    }

    public function addGroup(GroupCompetition $group): static
    {
        if (!$this->Groups->contains($group)) {
            $this->Groups->add($group);
            $group->setCompetition($this);
        }

        return $this;
    }

    public function removeGroup(GroupCompetition $group): static
    {
        if ($this->Groups->removeElement($group)) {
            // set the owning side to null (unless already changed)
            if ($group->getCompetition() === $this) {
                $group->setCompetition(null);
            }
        }

        return $this;
    }


}

src/Entity/OffreGestion/Contract.php
<?php

namespace App\Entity\OffreGestion;

use App\Repository\OffreGestion\ContractRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContractRepository::class)]
class Contract
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $Type = null;

    #[ORM\OneToOne(inversedBy: 'contract', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?offre $id_Contract = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getIdContract(): ?offre
    {
        return $this->id_Contract;
    }

    public function setIdContract(offre $id_Contract): static
    {
        $this->id_Contract = $id_Contract;

        return $this;
    }


}
    //id_Employer
    //id_Employee

src/Controller/CourseGestionController.php
<?php

namespace App\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\CourseGestion\Course;
use App\Form\AddCourseType;

class CourseGestionController extends AbstractController
{
    #[Route('/course/addCourse', name: 'addcourse')]
    public function addcourse(Request $req, ManagerRegistry $doctrine): Response
    {
        $course=new Course();
        $form=$this->createForm(AddCourseType::class,$course);

        $form->handleRequest($req);
        if ($form->isSubmitted()){
        $manager=$doctrine->getManager();
        $manager->persist($course);
        $manager->flush();
        return $this->redirectToRoute("addcourse");
        }
        //renvoyer le form vers la vue
      //  return $this->render("author/add.html.twig", ["myForm"=>$form->createView()]);
        return $this->renderForm("course_gestion/addCourse.twig", ["add_course"=>$form]);
    }
    #[Route('/course/show', name: 'show',defaults:["User"=>0])]
    public function show_list_courses($User,ManagerRegistry $doctrine,Request $request) :Response {
            $repository=$doctrine->getRepository(Course::class);
            $courses=$repository->findAll();
            //*
            if($courses)
                return $this->render("/course_gestion/showCourse.twig",
                ["User"=>$User,"courses"=>$courses]
        );
        else throw $this->createNotFoundException("error courses not found");//*/
    }
    #[Route('/course/show_user', name: 'specific_course_user')]
    public function specific_courses_user(ManagerRegistry $doctrine,Request $request) :Response {
            $repository=$doctrine->getRepository(Course::class);
            $courses=$repository->findAll();
            if($courses)
                return $this->render("/course_gestion/showCourse.twig",
            ["request"=>$request]
        );
        else throw $this->createNotFoundException("error courses not found");
    }

}

templates/course_gestion/addCourse.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="{{ asset('components/Form/assets/css/style.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/quill/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/quill/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/simple-datatables/style.css') }}" rel="stylesheet">
  <link href="{{ asset('components/Form/assets/vendor/simple-datatables/style.css') }}" rel="stylesheet">
</head>
<body>
   <section class="section">
      <div class="row">
        <div class="col-lg-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Event Details</h5>
              <!-- Event Details Form -->
              {{ form_start(Event) }}
                <div class="row mb-3">
                  <label for="event_name" class="col-sm-2 col-form-label required">Name</label>
                  <div class="col-sm-10">
                    {{ form_row(Event.name, {'attr': {'class': 'form-control', 'required': 'required', 'maxlength': '255'}}) }}
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="event_location" class="col-sm-2 col-form-label required">Location</label>
                  <div class="col-sm-10">
                    {{ form_row(Event.location, {'attr': {'class': 'form-control', 'required': 'required', 'maxlength': '255'}}) }}
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="event_type" class="col-sm-2 col-form-label required">Type</label>
                  <div class="col-sm-10">
                    {{ form_row(Event.type, {'attr': {'class': 'form-control', 'required': 'required', 'maxlength': '255'}}) }}
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="event_details" class="col-sm-2 col-form-label required">Details</label>
                  <div class="col-sm-10">
                    {{ form_row(Event.details, {'attr': {'class': 'form-control', 'required': 'required', 'maxlength': '255'}}) }}
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="event_city" class="col-sm-2 col-form-label required">City</label>
                  <div class="col-sm-10">
                    {{ form_row(Event.city, {'attr': {'class': 'form-control', 'required': 'required', 'maxlength': '255'}}) }}
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                  </div>
                </div>
              <!-- End Event Details Form -->
              {{ form_end(Event) }}
            </div>
          </div>
        </div>
      </div>
    </section>

  <script src="{{ asset('components/Form/assets/vendor/apexcharts/apexcharts.min.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/chart.js/chart.umd.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/echarts/echarts.min.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/quill/quill.min.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/simple-datatables/simple-datatables.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ asset('components/Form/assets/vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ asset('components/Form/assets/js/main.js') }}"></script>
</body>
</html>

templates/course_gestion/showCourse.twig
{% if courses is defined %}
    

{{ dump(courses) }}
{% for course in courses %}
{{ course.getId() }}    
{% endfor %}
{{ courses[0].getId() }}
{{ dump(courses[0]) }}
{% if courses is defined %}
    {% if courses is iterable %}
<table class="table">
    <thead>
        <tr>
        {% for key in ["course","Title","owner_Name","owner_Family_Name","Rate","price","buyers"] %}
                <th>{{key}}</th>
        {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% set number_of_courses = 0 %}
        {% for Course in courses %}
            <tr>
                <td>{{number_of_courses}}</td>
                 {% set number_of_courses=number_of_courses+1 %}
                 <td scope="row">{{Course.getTitle()}}</td>
                <td scope="row">{{Course.getowner().getName()}}</td>
                <td scope="row">{{Course.getowner().getFamilyName()}}</td>
                <td scope="row">{{Course.getRate()}}</td>
                <td scope="row">{{Course.getPrice()}}</td>
                <td scope="row">
                {% set users = Course.getUsers() %}
                    {% if users is defined %}
                        {% for user in users %}
                            {{user.getName()}}  
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

        
    {% endif %}
{% else %}
none
{% endif %}
{% else %}
{{ dump(request) }}
{% endif %}